dependencies:
- name: jx-flo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.52
- name: node-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.6.0
