dependencies:
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: cleanup
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.6.0
