dependencies:
- name: flo
  repository: http://jenkins-x-chartmuseum:8080
  version: 4.0.5
- name: jx-flo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.52
- name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.0.1
- name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.14.4
- name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.1.8
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.6.0
